<template>
  <div class="container padding-bottom-xl">
    <div class="row position-relative">
      <div class="col-12">
        <h1 class="font-xl font-color-light">Report</h1>
        <span class="font-sm font-color-light" v-if="generator">
          Generated by
          <span class="font-color-primary">{{generator}}({{version}})</span>
          , {{lastScan}} ({{scanDuration}}s)
        </span>
        <reportScoreResults :results="results" v-if="results"/>
      </div>
      <div class="col-12 col-lg-6" v-if="targets">
        <h3 class="font-color-light font-lg margin-top-sm">Hosts</h3>
        <div class="d-flex flex-column">
          <span
            v-for="(t, id) in targets"
            :key="id"
            class="font-color-secondary cursor-pointer margin-bottom-xs d-flex align-items-center"
            data-bs-toggle="modal"
            :data-bs-target="`#target_${id}`"
          >
          <span :href="`/hostname/${t.transport.hostname}/${t.transport.port}`"
            class="text-decoration-none target-icon-link font-color-secondary w-100">
            <div class="d-flex flex-column justify-content-between w-100">
                <div class="">
                    <div class="d-flex">
                      <customPill
                      class="margin-right-xxs d-flex align-items-center pb-0"
                      :label="t.scanning_status.monitoring === true ? 'Active' : 'Inactive' "
                      :type="t.scanning_status.monitoring === true ? 'success' : 'danger' "
                      />
                    </div>
                    <div class="d-flex flex-column">
                      <span v-for="(http, id) in t.http" :key="id" class="http-status mb-0"
                      :class="{ 'font-color-primary': http.status_code === 200, 'font-color-danger': http.status_code !== 200 }">
                      {{ http.title }}
                    </span>
                      <span class="d-block"><IconTarget class="margin-right-xxs target-icon" color="e2c878" />{{ t.transport.hostname }}:{{ t.transport.port }} <span class="font-color-light-20">{{ t.transport.peer_address }}</span></span>
                      <span v-if="t.error" class="d-block font-color-tertiary">{{ t.error[0] }} {{t.error[1]}}</span>
                    </div>
                </div>
                <div class="font-color-light-40">
                    {{ t.timeago }}
                </div>
            </div>
            </span>
          </span>
        </div>
        <slidingModal
          v-for="(target, targetModalId) in targets"
          :key="targetModalId"
          :id="`target_${targetModalId}`">
          <template #header>
            <div class="modal-header border-0 d-flex justify-content-start">
              <button
                    type="button"
                    class="btn-close m-0 p-0"
                    data-bs-dismiss="modal"
                    aria-label="Close"
                  >
                <IconArrowPrimary color="ffffff" class='modal-icon-report-close'/>
              </button>
            </div>
          </template>
          <template #content>
            <div class="modal-body">
              <loadingComponent class="loading" :class="{ inactive: !loading }" :active="loading" />
              <ValidationMessage :message='errorMessageScanHost' :type="errorMessageTypeScanHost" />
              <div class="d-flex flex-column flex-lg-row justify-content-between">
                <span class="font-color-secondary font-base-b">
                  <IconTarget class="target-icon" color="e2c878" />
                  {{target.transport.hostname}}:{{target.transport.port}}
                  <p class="font-color-light font-sm">
                    Peer Address: {{target.transport.peer_address}}
                  </p>
                </span>
                <p class="font-color-light">
                  Updated {{moment.utc(target.last_updated).fromNow()}}
                <br>
                <span class="font-color-light" v-if="target.scanning_status.queue_status">
                  {{ target.scanning_status.queue_status }} {{ moment.utc(target.scanning_status.queued_timestamp).fromNow()}}
                </span>
                </p>
                <div class="d-flex flex-sm-row">
                  <div class="font-base font-color-light margin-bottom-md">
                    <div class="d-flex flex-sm-row">
                      <span class="font-color-light font-base-b margin-top-xxs margin-right-xs">Monitoring</span>
                      <Toggle
                      :defaultChecked="target.scanning_status.monitoring"
                      @change="hostToggleChange($event, target.transport.hostname)"
                      />
                    </div>
                    <customPill
                      class=""
                      :label="target.scanning_status.monitoring === true ? 'Active' : 'Inactive' "
                      :type="target.scanning_status.monitoring === true ? 'success' : 'danger' "
                    />
                  </div>
                </div>
              </div>
              <div class="row margin-bottom-xxs">
                <div class="col-6 d-flex flex-column margin-bottom-sm">
                  <h3 class="font-color-light font-base-sb">
                    Certificates
                  </h3>
                  <span
                    v-for="(sha1_fingerprint, certIndex) in uniqueCertificates(target.tls.certificates)"
                    :key=certIndex
                    class="font-color-secondary font-sm word-break"
                  >
                    <a
                        target="_blank"
                        class="text-decoration-none font-color-secondary"
                        :href="`/certificate/${sha1_fingerprint}`"
                    >
                        <IconCertificate color="e2c878" class="cert-icon margin-right-sm" /><span title="See Certificate details">{{ commonNameFromSubject(getCertificate(sha1_fingerprint).subject) }}</span>
                    </a>
                  </span>
                </div>
                <div class="col-6">
                  <h3 class="font-color-secondary font-base-sb margin-top-sm">
                    <IconTarget class="target-icon" color="e2c878" />
                    Protocol
                  </h3>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Negotiated:
                    </span>
                    <span class="font-color-base font-color-light">
                      {{target.tls.protocol.negotiated}}
                    </span>
                  </p>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Preferred:
                    </span>
                    <span class="font-color-base font-color-light">
                      {{target.tls.protocol.preferred}}
                    </span>
                  </p>
                  <div class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Offered:
                    </span>
                    <div class="d-flex flex-column">
                      <span
                        class="font-color-base font-color-light"
                        v-for="(offered, offeredIndex) in target.tls.protocol.offered"
                        :key="offeredIndex"
                      >
                        {{offered}}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <template v-if="target.tls.client.expected_client_subjects.length">
                  <div class="col-6">
                    <span
                      class="font-color-base font-color-light"
                      v-for="(subject, subjectIndex) in target.tls.client.expected_client_subjects"
                      :key="subjectIndex"
                    >
                      {{subject}}
                    </span>
                  </div>
                </template>
                <div class="col-6">
                  <h3 class="font-color-secondary font-base-sb">
                    <IconTarget class="target-icon" color="e2c878" />
                    Cipher
                    <span
                      class="font-color-light font-sm"
                      :title="`${target.tls.cipher.offered_rfc.join('\n')}`"
                    >
                      ({{ target.tls.cipher.offered_rfc.length }} offered)
                    </span>
                  </h3>
                  <p class="margin-bottom-sm font-color-light">
                    <span class="font-base-sb">Negotiated:</span> <span class="font-base">{{target.tls.cipher.negotiated}}</span>
                  </p>
                  <p class="margin-bottom-sm font-color-light">
                    <span class="font-base-sb">Negotiated Bits:</span> <span class="font-base">{{target.tls.cipher.negotiated_bits}}</span>
                  </p>
                </div>
                <div class="col-lg-6 col-12">
                  <h3 class="font-color-secondary font-base-sb margin-top-sm">
                    <IconTarget class="target-icon" color="e2c878" />
                    Session Resumption
                  </h3>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Cache Mode:
                    </span>
                    <span class="font-color-base font-color-light">
                      {{target.tls.session_resumption.cache_mode}}
                    </span>
                  </p>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Ticket Hint:
                    </span>
                    <span class="font-color-base font-color-light text-capitalize">
                      {{target.tls.session_resumption.ticket_hint}}
                    </span>
                  </p>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Tickets:
                    </span>
                    <span class="font-color-base font-color-light text-capitalize">
                      {{target.tls.session_resumption.tickets}}
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </template>
        </slidingModal>
      </div>
      <div class="col-12 col-lg-6" v-if="certificates">
        <reportCertificates :slicedCerts="slicedCerts" />
      </div>
      <div class="col-12 col-lg-6" v-else>
        <h3 class="font-color-light font-lg margin-top-sm">Certificates</h3>
        <div class="d-flex flex-column font-color-light bg-dark-40 padding-sm border-radius-sm">
          No Certificates Observed
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-12 margin-top-sm">
        <div class="filter-results">
          <div class="d-flex justify-content-start padding-left-sm">
            <div class="d-flex align-items-center">
              <input type="checkbox" id="checkPass" class="margin-right-sm custom-checkbox" v-model="resultsFilter.pass">
              <label for="checkPass" class="margin-right-md font-xs font-color-light">Passes ({{results.pass}})</label>
            </div>
            <div class="d-flex align-items-center">
              <input type="checkbox" id="checkFail" class="margin-right-sm custom-checkbox" v-model="resultsFilter.fail">
              <label for="checkFail" class="margin-right-md font-xs font-color-light">Failures ({{results.fail}})</label>
            </div>

            <div class="d-flex align-items-center">
              <input type="checkbox" id="checkWarn" class="margin-right-sm custom-checkbox" v-model="resultsFilter.warn">
              <label for="checkWarn" class="margin-right-md font-xs font-color-light">Warnings ({{results.warn}})</label>
            </div>

            <div class="d-flex align-items-center">
              <input type="checkbox" id="checkInfo" class="margin-right-sm custom-checkbox" v-model="resultsFilter.info">
              <label for="checkInfo" class="margin-right-md font-xs font-color-light">Insights ({{results.info}})</label>
            </div>

          </div>
          <div class="d-flex justify-content-start padding-left-sm">

          </div>
        </div>
        <div v-for="(evaluation, evalIndex) in evaluations" :key="`${evalIndex}`">
          <Dropdown
              :id="`headingEvaluate${evalIndex}`"
              :target="`collapseEvaluate${evalIndex}`"
              parent="accordion"
              :defaultShow=false
              :defaultCollapsed=true
              buttonClasses="font-lg text-left report-dropdown font-color-light w-100 d-flex justify-content-left border-none padding-xxs"
              contentClasses=" bg-dark-20 report-dropdown-content tpadding-md font-color-light font-base"
              v-if="
              evaluation.result_level === (resultsFilter.pass ? 'pass' : '') ||
              evaluation.result_level === (resultsFilter.warn ? 'warn' : '') ||
              evaluation.result_level === (resultsFilter.fail ? 'fail' : '') ||
              evaluation.result_level === (resultsFilter.info ? 'info' : '')
              "
              >
                <template v-slot:header class="w-100" >
                  <div class="font-base d-flex flex-column justify-content-between font-color-primary w-100 align-items-start">
                      <div class="d-flex w-100">
                        <ThreatIcon />
                        <div class="d-flex flex-column">
                          <div class="d-flex align-items-center">
                            <span class="margin-right-xxs font-sm-b font-color-secondary">
                              {{evaluation?.rule_id}}
                            </span>
                            <span class="font-color-lighter font-xs-sb">
                              {{evaluation?.name}}
                            </span>
                          </div>
                          <span
                            class="font-xs"
                            :class="{
                              'font-color-warning': (evaluation?.result_level === 'warn'),
                              'font-color-danger': (evaluation?.result_level === 'fail'),
                              'font-color-primary': (evaluation?.result_level === 'pass'),
                              'font-color-light-60': (evaluation?.result_level === 'info'),
                            }"
                          >
                            {{evaluation?.result_label}}
                          </span>
                          <span class="font-sm" v-if="evaluation.transport">
                            <a :href="`/hostname/${evaluation.transport.hostname}/${evaluation.transport.port}`" class="font-color-lighter-60 text-decoration-none">
                              <IconTarget class="link-icon margin-right-xxs" color="e2c878"/>
                              <span class="font-color-lighter-60">
                                {{evaluation.transport.hostname}}:{{evaluation.transport.port}}
                              </span>
                            </a>
                          </span>
                          <span class="font-sm" v-if="evaluation?.metadata?.certificate_subject && evaluation?.metadata?.sha1_fingerprint">
                            <a :href="`/certificate/${evaluation.metadata.sha1_fingerprint}`" class="font-color-lighter-60 text-decoration-none">
                              <IconCertificate class="link-icon margin-right-xxs" color="e2c878"/>
                              <span class="font-color-lighter-60">
                                {{evaluation.metadata.certificate_subject}}
                              </span>
                            </a>
                          </span>
                        </div>
                      </div>
                    </div>
                </template>
                <template v-slot:content>
                  <div class="row">
                    <div class="col-12 col-lg-6 padding-top-sm">
                      <span class="font-xs pre-line">
                        {{evaluation?.description}}
                      </span>
                    </div>
                    <div class="col-12 col-lg-6 d-flex flex-column">
                      <template v-if="evaluation?.references.length > 0">
                        <span class="font-sm-sb font-color-light margin-top-sm">References</span>
                        <span
                          class="margin-top-xxs"
                          v-for="(ev, index) in evaluation?.references"
                          :key="index"
                        >
                          <IconLink color="1abb9c" class="link-icon margin-right-xxs" />
                          <a
                            target="_blank"
                            :href="ev.url"
                            class="font-xs-sb font-color-primary"
                          >{{ev.name}}</a>
                        </span>
                      </template>
                      <div class="col-12 col-lg-6 font-sm font-color-light d-flex flex-column margin-top-sm" v-if="evaluation?.metadata">
                        <div class="d-flex" v-if="evaluation?.metadata?.reason">
                          <span class="font-sm-sb margin-right-xxs">Reason:</span><span>{{evaluation?.metadata?.reason}}</span>
                        </div>
                        <div class="d-flex margin-top-sm" v-if="evaluation?.metadata?.certificate_version || evaluation?.metadata?.certificate_subject || evaluation?.metadata?.sha1_fingerprint">
                          <span class="font-sm-sb margin-right-xxs">Certificate</span>
                          <div class="d-flex margin-right-xxs" v-if="evaluation?.metadata?.certificate_version">
                            <span>version {{evaluation?.metadata.certificate_version}}</span>
                          </div>
                        </div>
                        <div class="d-flex" v-if="evaluation?.metadata?.public_key_size">
                          <span class="font-sm-sb margin-right-xxs">Public Key:</span>{{evaluation?.metadata.public_key_type}}{{evaluation?.metadata.public_key_size}}
                        </div>
                      </div>
                      <a
                        v-if="evaluation?.metadata?.certificate_subject && evaluation?.metadata?.sha1_fingerprint"
                        class="font-color-secondary font-sm word-break"
                        :href="`/certificate/${evaluation?.metadata.sha1_fingerprint}`"
                      >
                        <IconCertificate color="e2c878" class="target-icon margin-right-xxs" />
                        <span title="See Certificate details">
                          {{evaluation?.metadata.certificate_subject}}
                        </span>
                      </a>
                      <a
                        v-else-if="evaluation?.metadata?.sha1_fingerprint"
                        class="font-color-secondary font-sm word-break"
                        :href="`/certificate/${evaluation?.metadata.sha1_fingerprint}`"
                      >
                        <IconCertificate color="e2c878" class="target-icon margin-right-xxs" />
                        <span title="See Certificate details">
                          {{evaluation?.metadata.sha1_fingerprint}}
                        </span>
                      </a>

                    </div>
                    <div
                      class="col-12 d-flex flex-column padding-top-sm"
                      v-if="evaluation?.compliance?.length > 0"
                    >
                      <h3 class="font-base-sb font-color-light" v-if="evaluation?.compliance?.items">Compliance</h3>
                      <div
                        :id="`complianceSection${evaluation?.rule_id.replace(/\./g, '-')}`"
                      >
                        <div
                          v-for="(compliance, index) in evaluation.compliance"
                          :key="index"
                          >
                          <div v-if="compliance?.items?.length > 0">
                            {{ compliance.compliance }} {{ compliance.version }}
                            <div class="d-flex flex-wrap">
                              <button
                                v-for="(comp, compIndex) in compliance.items"
                                class="pill w-auto margin-right-xxs font-xs-sb"
                                data-bs-toggle="collapse"
                                type="button"
                                aria-expanded="false"
                                :key="compIndex"
                                :data-bs-target="`#multiCollapseCompliance${evaluation?.rule_id?.replace(/\./g, '-')}-${comp?.requirement?.replace(/\./g, '-')}`"
                                :data-bs-parent="`#complianceSection${evaluation?.rule_id?.replace(/\./g, '-')}`"
                                :aria-controls="`multiCollapseCompliance${evaluation?.rule_id?.replace(/\./g, '-')}-${comp?.requirement?.replace(/\./g, '-')}`"
                              >
                                Req: {{comp.requirement}}
                              </button>
                            </div>

                            <div class="row margin-bottom-sm">
                              <div class="col">
                                <div
                                v-for="(comp, compIndex) in compliance.items"
                                :key="compIndex"
                                class="collapse multi-collapse"
                                :id="`multiCollapseCompliance${evaluation?.rule_id?.replace(/\./g, '-')}-${comp?.requirement?.replace(/\./g, '-')}`"
                                :data-bs-parent="`#complianceSection${evaluation?.rule_id?.replace(/\./g, '-')}`"
                                >
                                  <div class="card card-body bg-dark-40 font-xs pre-line">
                                    {{comp.description}}
                                  </div>
                                </div>
                              </div>
                            </div>

                          </div>
                        </div>
                      </div>

                    </div>
                    <div
                      class="col-12 d-flex flex-column padding-top-sm"
                      v-if="evaluation?.threats?.length > 0"
                    >
                      <h3 class="font-base-sb font-color-light margin-bottom-lg">Threats</h3>
                        <div v-for="(threat, threatIndex) in evaluation.threats"
                          class="d-flex flex-column"
                          :key="threatIndex"
                          >
                          <div class="threat-item-container d-flex row padding-left-sm padding-right-sm">
                            <threatItem :threat="threat" :evalIndex="evalIndex" :threatIndex="threatIndex" />
                          </div>
                          <div class="col-12 col-lg-4">
                            <div class="threat-separator-container">
                              <span class="threat-separator"></span>
                            </div>
                          </div>
                        </div>
                    </div>
                  </div>
                </template>
          </Dropdown>
        </div>
      </div>
    </div>

  </div>
</template>
<script setup>
import moment from "moment";
import IconLink from "@/components/icons/IconLink.vue";
import IconTarget from "@/components/icons/IconTarget.vue";
import reportScoreResults from "@/components/general/reportScoreResults.vue";
import ExpandSection from "@/components/general/ExpandSection.vue";
import Dropdown from "@/components/general/Dropdown.vue"
import threatItem from "@/components/general/threatItem.vue"
import IconClose from "@/components/icons/IconClose.vue";
import ThreatIcon from "@/components/icons/ThreatIcon.vue";
import IconCertificate from "@/components/icons/IconCertificate.vue";
import Toggle from "@/components/general/Toggle.vue"
import ValidationMessage from "@/components/general/ValidationMessage.vue"
import loadingComponent from "@/components/general/loadingComponent.vue"
import IconArrowPrimary from "@/components/icons/IconArrowPrimary.vue";
import IconChevron from "@/components/icons/IconChevron.vue"
import customPill from "@/components/general/customPill.vue";
import slidingModal from "@/components/general/slidingModal.vue";
import reportCertificates from "@/components/general/reportCertificates.vue"
</script>

<script>
export default {
  components: {
    IconLink,
    IconTarget,
    reportScoreResults,
    ExpandSection,
    Dropdown,
    threatItem,
    IconClose,
    ThreatIcon,
    IconCertificate,
    Toggle,
    ValidationMessage,
    loadingComponent,
    IconArrowPrimary,
    customPill,
    slidingModal,
    IconChevron,
    reportCertificates
  },

  props: [
    "generator",
    "version",
    "account_name",
    "client_name",
    "project_name",
    "targets",
    "date",
    "execution_duration_seconds",
    "score",
    "results",
    "certificates",
    "results_uri",
    "config",
    "flags",
    "evaluations",
  ],
  data() {
      return {
          loading: false,
          errorMessage: '',
          errorMessageType: '',
          errorMessageScanHost: '',
          errorMessageTypeScanHost: '',
          resultsFilter: {
            'pass': false,
            'fail': true,
            'warn': true,
            'info': false,
          }
      }
  },
  methods: {
      async hostToggleChange(e, hostname) {
          this.loading = true
          try {
            if (e.target.checked === true) {
                const response = await Api.get(`/scanner/monitor/${hostname}`)
                if (response.status !== 200) {
                    this.errorMessageScanHost = `${response.status} ${response.statusText}: Sorry, we couldn't complete this action.`
                    this.errorMessageTypeScanHost = "error";
                    this.loading = false
                    e.target.checked = false
                    return;
                }
                this.errorMessageScanHost = `Monitoring host.`
                this.errorMessageTypeScanHost = "success";
                for (const target of this.targets) {
                  if (hostname === target.transport.hostname) {
                    target.scanning_status.monitoring = true
                  }
                }
            } else {
                const response = await Api.get(`/scanner/deactivate/${hostname}`)
                if (response.status !== 200) {
                    this.errorMessageScanHost = `${response.status} ${response.statusText}: Sorry, we couldn't complete this action.`
                    this.errorMessageTypeScanHost = "error";
                    this.loading = false
                    e.target.checked = false
                    return;
                }
                this.errorMessageScanHost = `No longer monitoring host.`
                this.errorMessageTypeScanHost = "success";
                for (const target of this.targets) {
                  if (hostname === target.transport.hostname) {
                    target.scanning_status.monitoring = false
                  }
                }
            }
          } catch (error) {
            this.errorMessageScanHost = error.name === 'AbortError' ? "Request timed out, please try refreshing the page." : `${error.name} ${error.message}. Couldn't complete this action.`
            this.errorMessageTypeScanHost = "error"
            e.target.checked = false
          }
          this.loading = false
      },
      swiperNext(){
        this.$refs.certificateSwiper
      },
      commonNameFromSubject(subject) {
          if (typeof subject !== 'string' || subject.indexOf('CN=') === -1) {
              return subject
          }
          return subject.split(',').filter(p => p.trim().startsWith('CN=')).join('').replace(/CN=/g, '')
      },
      getCertificate(sha1_fingerprint) {
          return this.certificates.filter(cert => cert.sha1_fingerprint === sha1_fingerprint).pop()
      },
      uniqueCertificates(sha1Fingerprints){
          const uniq = new Set(sha1Fingerprints)
          return [...uniq]
      },
  },
  computed: {
    slicedCerts() {
      let certificate_chains = []
      function next_certs(SKI, arr) {
          for (const cert of cert_list) {
            if (cert.authority_key_identifier === SKI) {
                // console.log(cert.type, cert.subject_key_identifier, cert.subject)
                arr.push(cert)
                next_certs(cert.subject_key_identifier, arr)
            }
          }
      }
      let cert_list = this.certificates.slice()
      for (const cert of cert_list) {
        if (cert.type === "root") {
            let chain = [cert]
            cert_list = cert_list.filter(item => item !== cert)
            // console.log(cert.type, cert.subject_key_identifier, cert.subject)
            next_certs(cert.subject_key_identifier, chain)
            certificate_chains.push(chain.reverse())
        }
      }
      return certificate_chains
    },
    lastScan() {
      return moment.utc(this.date).fromNow();
    },
    scanDuration(){
      return Math.floor(this.execution_duration_seconds);
    }
  }
};
</script>

<style lang="scss">
.report {
  &-item {
    cursor: pointer;
    z-index: 10;
    height: 20px;
  }
}

.cert-icon, .target-icon {
    height: 25px;
    width: 25px;
}

.link-icon {
    height: 20px;
    width: 20px;
}

.report-dropdown {
    background: color("dark-20");
    border-bottom: 1px solid color("dark-60");
    align-items: center;
    padding: spacers("xs");

    .expand-icon {
        transform: rotate(180deg);
        width: 25px;
        height: 25px;
    }

    &.collapsed {
        .expand-icon {
            transform: rotate(0deg);
        }
    }

    &-content {
        border-bottom: 1px solid color("dark-60");
        padding: spacers("xs");
    }
}

.custom-swiper-button {
  position: relative;
  border-radius: radius("sm");
  padding: 0 padding("xs");
  background: color("dark-60");
  color: color(light);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: 0.2s linear;
  border: 1px solid color("dark");

  &:hover {
    border: 1px solid color("secondary");
    color: color("secondary");
  }

  &:disabled {
    color: color("light-20");
    background: none;
    border: 1px solid color("light-20");
    display: none;
  }
}

.modal-icon-report-close {
    width: 25px;
    height: 25px;
    // transform: rotate(180deg);
}

.pill {
    color: color("light");
    background: color("primary");
    border: 1px solid color("primary");

    &.collapsed {
        background: none;
        color: color("primary");
        border: 1px solid color("primary");
    }
}

.truncate-ellipsis {
    width: 100%;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

.filter-results {
  background: color('dark-60');
  backdrop-filter: blur(8px);
  height: 60px;
  // position: sticky;
  // top: 65px;
  display: flex;
  justify-content: flex-start;
  label {
    cursor: pointer;
  }
}

.custom-checkbox {
  appearance: unset;
  width: 15px;
  height: 15px;
  background: color('light-20');
  transition: 0.2s linear;
  border-radius: 5px;
  cursor: pointer;

  &:checked {
    background: rgb(26, 187, 156);
    display: flex;
    align-items: center;
    justify-content: center;

    &:after {
      content: "\2713";
      color: color("dark");
      line-height: 15px;
      font-size: 10px;
    }
  }
}
</style>
