<template>
  <div class="container padding-bottom-xl">
    <div class="row position-relative">
      <div class="col-12">
        <h1 class="font-xl font-color-light">Report</h1>
        <span class="font-sm font-color-light" v-if="generator">
          Generated by
          <span class="font-color-primary">{{ generator }}({{ version }})</span>
          , {{ lastScan }} ({{ scanDuration }}s)
        </span>
        <ReportScoreResults :results="results" v-if="results" />
      </div>
      <div class="col-12 col-lg-6" v-if="targets">
        <h3 class="font-color-light font-lg margin-top-sm">Hosts</h3>
        <div class="d-flex flex-column">
          <span
            v-for="(t, id) in targets"
            :key="id"
            class="font-color-secondary cursor-pointer margin-bottom-xs d-flex align-items-center"
            data-bs-toggle="modal"
            :data-bs-target="`#target_${id}`"
          >
            <span
              class="text-decoration-none target-icon-link font-color-secondary w-100"
            >
              <div class="d-flex flex-column justify-content-between w-100">
                <div>
                  <div class="d-flex">
                    <CustomPill
                      class="margin-right-xxs d-flex align-items-center pb-0"
                      :label="
                        t.scanning_status.monitoring === true
                          ? 'Active'
                          : 'Inactive'
                      "
                      :type="
                        t.scanning_status.monitoring === true
                          ? 'success'
                          : 'danger'
                      "
                    />
                  </div>
                  <div class="d-flex flex-column">
                    <span
                      v-for="(http, id) in t.http"
                      :key="id"
                      class="http-status mb-0"
                      :class="{
                        'font-color-primary': http.status_code === 200,
                        'font-color-danger': http.status_code !== 200,
                      }"
                    >
                      {{ http.title }}
                    </span>
                    <span class="d-block"
                      ><IconTarget
                        class="margin-right-xxs target-icon"
                        color="e2c878"
                      />{{ t.transport.hostname }}:{{ t.transport.port }}
                      <span class="font-color-light-20">{{
                        t.transport.peer_address
                      }}</span></span
                    >
                    <span v-if="t.error" class="d-block font-color-tertiary"
                      >{{ t.error[0] }} {{ t.error[1] }}</span
                    >
                  </div>
                </div>
                <div class="font-color-light-40">
                  {{ t.timeago }}
                </div>
              </div>
            </span>
          </span>
        </div>
        <SlidingModal
          v-for="(target, targetModalId) in targets"
          :key="targetModalId"
          :id="`target_${targetModalId}`"
        >
          <template #header>
            <div class="modal-header border-0 d-flex justify-content-start">
              <button
                type="button"
                class="btn-close m-0 p-0"
                data-bs-dismiss="modal"
                aria-label="Close"
              >
                <IconArrowPrimary
                  color="ffffff"
                  class="modal-icon-report-close"
                />
              </button>
            </div>
          </template>
          <template #content>
            <div class="modal-body">
              <LoadingComponent
                class="loading"
                :class="{ inactive: !loading }"
                :active="loading"
              />
              <ValidationMessage
                :message="errorMessageScanHost"
                :type="errorMessageTypeScanHost"
              />
              <div
                class="d-flex flex-column flex-lg-row justify-content-between"
              >
                <span class="font-color-secondary font-base-b">
                  <IconTarget class="target-icon" color="e2c878" />
                  {{ target.transport.hostname }}:{{ target.transport.port }}
                  <p class="font-color-light font-sm">
                    Peer Address: {{ target.transport.peer_address }}
                  </p>
                </span>
                <p class="font-color-light">
                  Updated {{ moment.utc(target.last_updated).fromNow() }}
                  <br />
                  <span
                    class="font-color-light"
                    v-if="target.scanning_status.queue_status"
                  >
                    {{ target.scanning_status.queue_status }}
                    {{
                      moment
                        .utc(target.scanning_status.queued_timestamp)
                        .fromNow()
                    }}
                  </span>
                </p>
                <div class="d-flex flex-sm-row">
                  <div class="font-base font-color-light margin-bottom-md">
                    <div class="d-flex flex-sm-row">
                      <span
                        class="font-color-light font-base-b margin-top-xxs margin-right-xs"
                        >Monitoring</span
                      >
                      <Toggle
                        :defaultChecked="target.scanning_status.monitoring"
                        @change="
                          hostToggleChange($event, target.transport.hostname)
                        "
                      />
                    </div>
                    <CustomPill
                      class=""
                      :label="
                        target.scanning_status.monitoring === true
                          ? 'Active'
                          : 'Inactive'
                      "
                      :type="
                        target.scanning_status.monitoring === true
                          ? 'success'
                          : 'danger'
                      "
                    />
                  </div>
                </div>
              </div>
              <div class="row margin-bottom-xxs">
                <div class="col-6 d-flex flex-column margin-bottom-sm">
                  <h3 class="font-color-light font-base-sb">Certificates</h3>
                  <span
                    v-for="(sha1_fingerprint, certIndex) in uniqueCertificates(
                      target.tls.certificates
                    )"
                    :key="certIndex"
                    class="font-color-secondary font-sm word-break"
                  >
                    <a
                      target="_blank"
                      class="text-decoration-none font-color-secondary"
                      :href="`/certificate/${sha1_fingerprint}`"
                    >
                      <IconCertificate
                        color="e2c878"
                        class="cert-icon margin-right-sm"
                      /><span title="See Certificate details">{{
                        commonNameFromSubject(
                          getCertificate(sha1_fingerprint).subject
                        )
                      }}</span>
                    </a>
                  </span>
                </div>
                <div class="col-6">
                  <h3 class="font-color-secondary font-base-sb margin-top-sm">
                    <IconTarget class="target-icon" color="e2c878" />
                    Protocol
                  </h3>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Negotiated:
                    </span>
                    <span class="font-color-base font-color-light">
                      {{ target.tls.protocol.negotiated }}
                    </span>
                  </p>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Preferred:
                    </span>
                    <span class="font-color-base font-color-light">
                      {{ target.tls.protocol.preferred }}
                    </span>
                  </p>
                  <div class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Offered:
                    </span>
                    <div class="d-flex flex-column">
                      <span
                        class="font-color-base font-color-light"
                        v-for="(offered, offeredIndex) in target.tls.protocol
                          .offered"
                        :key="offeredIndex"
                      >
                        {{ offered }}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
              <div class="row">
                <template
                  v-if="target.tls.client.expected_client_subjects.length"
                >
                  <div class="col-6">
                    <span
                      class="font-color-base font-color-light"
                      v-for="(subject, subjectIndex) in target.tls.client
                        .expected_client_subjects"
                      :key="subjectIndex"
                    >
                      {{ subject }}
                    </span>
                  </div>
                </template>
                <div class="col-6">
                  <h3 class="font-color-secondary font-base-sb">
                    <IconTarget class="target-icon" color="e2c878" />
                    Cipher
                    <span
                      class="font-color-light font-sm"
                      :title="`${target.tls.cipher.offered_rfc.join('\n')}`"
                    >
                      ({{ target.tls.cipher.offered_rfc.length }} offered)
                    </span>
                  </h3>
                  <p class="margin-bottom-sm font-color-light">
                    <span class="font-base-sb">Negotiated:</span>
                    <span class="font-base">{{
                      target.tls.cipher.negotiated
                    }}</span>
                  </p>
                  <p class="margin-bottom-sm font-color-light">
                    <span class="font-base-sb">Negotiated Bits:</span>
                    <span class="font-base">{{
                      target.tls.cipher.negotiated_bits
                    }}</span>
                  </p>
                </div>
                <div class="col-lg-6 col-12">
                  <h3 class="font-color-secondary font-base-sb margin-top-sm">
                    <IconTarget class="target-icon" color="e2c878" />
                    Session Resumption
                  </h3>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Cache Mode:
                    </span>
                    <span class="font-color-base font-color-light">
                      {{ target.tls.session_resumption.cache_mode }}
                    </span>
                  </p>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Ticket Hint:
                    </span>
                    <span
                      class="font-color-base font-color-light text-capitalize"
                    >
                      {{ target.tls.session_resumption.ticket_hint }}
                    </span>
                  </p>
                  <p class="margin-bottom-sm">
                    <span class="font-base-sb font-color-light">
                      Tickets:
                    </span>
                    <span
                      class="font-color-base font-color-light text-capitalize"
                    >
                      {{ target.tls.session_resumption.tickets }}
                    </span>
                  </p>
                </div>
              </div>
            </div>
          </template>
        </SlidingModal>
      </div>
      <div class="col-12 col-lg-6" v-if="certificates">
        <ReportCertificates :slicedCerts="slicedCerts" />
      </div>
      <div class="col-12 col-lg-6" v-else>
        <h3 class="font-color-light font-lg margin-top-sm">Certificates</h3>
        <div
          class="d-flex flex-column font-color-light bg-dark-40 padding-sm border-radius-sm"
        >
          No Certificates Observed
        </div>
      </div>
    </div>

    <div class="row">
      <EvaluationItems
        :evaluations="evaluations"
        :results="results"
        :resultsFilter="resultsFilter"
      />
    </div>
  </div>
</template>
<script setup>
import moment from "moment";
import IconLink from "@/components/icons/IconLink.vue";
import IconTarget from "@/components/icons/IconTarget.vue";
import ReportScoreResults from "@/components/general/ReportScoreResults.vue";
import ExpandSection from "@/components/general/ExpandSection.vue";
import Dropdown from "@/components/general/Dropdown.vue";
import IconClose from "@/components/icons/IconClose.vue";
import ThreatIcon from "@/components/icons/ThreatIcon.vue";
import IconCertificate from "@/components/icons/IconCertificate.vue";
import Toggle from "@/components/general/Toggle.vue";
import ValidationMessage from "@/components/general/ValidationMessage.vue";
import LoadingComponent from "@/components/general/LoadingComponent.vue";
import IconArrowPrimary from "@/components/icons/IconArrowPrimary.vue";
import IconChevron from "@/components/icons/IconChevron.vue";
import CustomPill from "@/components/general/CustomPill.vue";
import SlidingModal from "@/components/general/SlidingModal.vue";
import ReportCertificates from "@/components/general/ReportCertificates.vue";
import EvaluationItems from "@/components/EvaluationItems.vue";
</script>

<script>
export default {
  components: {
    IconLink,
    IconTarget,
    ReportScoreResults,
    ExpandSection,
    Dropdown,
    IconClose,
    ThreatIcon,
    IconCertificate,
    Toggle,
    ValidationMessage,
    LoadingComponent,
    IconArrowPrimary,
    CustomPill,
    SlidingModal,
    IconChevron,
    ReportCertificates,
    EvaluationItems,
  },

  props: [
    "generator",
    "version",
    "account_name",
    "client_name",
    "project_name",
    "targets",
    "date",
    "execution_duration_seconds",
    "score",
    "results",
    "certificates",
    "results_uri",
    "config",
    "flags",
    "evaluations",
  ],
  data() {
    return {
      loading: false,
      errorMessage: "",
      errorMessageType: "",
      errorMessageScanHost: "",
      errorMessageTypeScanHost: "",
      resultsFilter: {
        pass: false,
        fail: true,
        warn: true,
        info: false,
      },
    };
  },
  methods: {
    async hostToggleChange(e, hostname) {
      this.loading = true;
      try {
        if (e.target.checked === true) {
          const response = await Api.get(`/scanner/monitor/${hostname}`);
          if (response.status !== 200) {
            this.errorMessageScanHost = `${response.status} ${response.statusText}: Sorry, we couldn't complete this action.`;
            this.errorMessageTypeScanHost = "error";
            this.loading = false;
            e.target.checked = false;
            return;
          }
          this.errorMessageScanHost = `Monitoring host.`;
          this.errorMessageTypeScanHost = "success";
          for (const target of this.targets) {
            if (hostname === target.transport.hostname) {
              target.scanning_status.monitoring = true;
            }
          }
        } else {
          const response = await Api.get(`/scanner/deactivate/${hostname}`);
          if (response.status !== 200) {
            this.errorMessageScanHost = `${response.status} ${response.statusText}: Sorry, we couldn't complete this action.`;
            this.errorMessageTypeScanHost = "error";
            this.loading = false;
            e.target.checked = false;
            return;
          }
          this.errorMessageScanHost = `No longer monitoring host.`;
          this.errorMessageTypeScanHost = "success";
          for (const target of this.targets) {
            if (hostname === target.transport.hostname) {
              target.scanning_status.monitoring = false;
            }
          }
        }
      } catch (error) {
        this.errorMessageScanHost =
          error.name === "AbortError"
            ? "Request timed out, please try refreshing the page."
            : `${error.name} ${error.message}. Couldn't complete this action.`;
        this.errorMessageTypeScanHost = "error";
        e.target.checked = false;
      }
      this.loading = false;
    },
    swiperNext() {
      this.$refs.certificateSwiper;
    },
    commonNameFromSubject(subject) {
      if (typeof subject !== "string" || subject.indexOf("CN=") === -1) {
        return subject;
      }
      return subject
        .split(",")
        .filter((p) => p.trim().startsWith("CN="))
        .join("")
        .replace(/CN=/g, "");
    },
    getCertificate(sha1_fingerprint) {
      return this.certificates
        .filter((cert) => cert.sha1_fingerprint === sha1_fingerprint)
        .pop();
    },
    uniqueCertificates(sha1Fingerprints) {
      const uniq = new Set(sha1Fingerprints);
      return [...uniq];
    },
  },
  computed: {
    slicedCerts() {
      let certificate_chains = [];
      function next_certs(SKI, arr) {
        for (const cert of cert_list) {
          if (cert.authority_key_identifier === SKI) {
            // console.log(cert.type, cert.subject_key_identifier, cert.subject)
            arr.push(cert);
            next_certs(cert.subject_key_identifier, arr);
          }
        }
      }
      let cert_list = this.certificates.slice();
      for (const cert of cert_list) {
        if (cert.type === "root") {
          let chain = [cert];
          cert_list = cert_list.filter((item) => item !== cert);
          // console.log(cert.type, cert.subject_key_identifier, cert.subject)
          next_certs(cert.subject_key_identifier, chain);
          certificate_chains.push(chain.reverse());
        }
      }
      return certificate_chains;
    },
    lastScan() {
      return moment.utc(this.date).fromNow();
    },
    scanDuration() {
      return Math.floor(this.execution_duration_seconds);
    },
  },
};
</script>

<style lang="scss">
.report-item {
  cursor: pointer;
  z-index: 10;
  height: 20px;
}

.cert-icon,
.target-icon {
  height: 25px;
  width: 25px;
}

.link-icon {
  height: 20px;
  width: 20px;
}

.custom-swiper-button {
  position: relative;
  border-radius: radius("sm");
  padding: 0 padding("xs");
  background: color("dark-60");
  color: color(light);
  display: flex;
  align-items: center;
  justify-content: center;
  transition: 0.2s linear;
  border: 1px solid color("dark");

  &:hover {
    border: 1px solid color("secondary");
    color: color("secondary");
  }

  &:disabled {
    color: color("light-20");
    background: none;
    border: 1px solid color("light-20");
    display: none;
  }
}

.modal-icon-report-close {
  width: 25px;
  height: 25px;
  // transform: rotate(180deg);
}

.pill {
  color: color("light");
  background: color("primary");
  border: 1px solid color("primary");

  &.collapsed {
    background: none;
    color: color("primary");
    border: 1px solid color("primary");
  }
}
</style>
